language: rust

cache:
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

rust: nightly

install:
  - echo "$DEPLOY_PRIVATE_KEY" | base64 -d > $HOME/.ssh/id_travis
  - chmod 600 $HOME/.ssh/id_travis
  - ssh-add $HOME/.ssh/id_travis
  - cargo web --version || cargo install --force --git https://github.com/untitaker/cargo-web/ --branch no-newline-before-doctype cargo-web
  - rm -rf ./target/deploy/
  - cargo web deploy --release --target wasm32-unknown-unknown
  - |
    set -e
    if [ "$TRAVIS_RUST_VERSION" = nightly ] &&
       [ "$TRAVIS_PULL_REQUEST" = false ] &&
       [ "$TRAVIS_BRANCH" = master ]; then
      git clone https://github.com/davisp/ghp-import.git
      ./ghp-import/ghp_import.py \
        -n -p -f -m "Site deploy" -b gh-pages \
        -r git@github.com:$TRAVIS_REPO_SLUG.git \
        ./target/deploy/
      echo "Uploaded documentation"
    fi

script: true
