[package]
name = "piinguin"
version = "0.1.0"
authors = ["Sentry <hello@sentry.io>"]

[dependencies]
yew = { git = "https://github.com/DenisKolodin/yew", features = ["toml", "yaml", "msgpack", "cbor"] }
stdweb = "*"
marshal = { git = "https://github.com/getsentry/marshal", rev = "2383b8114c6ee5b003a90f91a343150a3f3833de" }
serde = "1.0.76"
failure = "*"
serde_json = "*"

[patch.crates-io]
serde = { git = "https://github.com/mitsuhiko/serde", rev = "880a8c0181ad7202950f24cc8f6872994913441d" }
serde_derive = { git = "https://github.com/mitsuhiko/serde", rev = "880a8c0181ad7202950f24cc8f6872994913441d" }
